run:
  skip-dirs:
    - testdata

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 10
  golint:
    min-confidence: 0
  govet:
    check-shadowing: true
  goconst:
    min-occurrences: 4
  gofmt:
    simplify: true
  lll:
    line-length: 128
  funlen:
    lines: 100
  gocritic:
    disabled-checks:
      - paramTypeCombine
      - emptyStringTest
      - ifElseChain
      - commentFormatting
      - unnamedResult
    enabled-tags:
      - performance
      - diagnostic
      - style
  wsl:
    allow-assign-and-call: false

linters:
  enable-all: true
  #disable-all: true
  disable:
    - godox

issues:
  exclude-use-default: false
  exclude-rules:
    - text: "package comment should not have leading space"
      linters:
        - golint
    - text: "should have a package comment, unless it's in another file for this package"
      linters:
        - golint
    - text: "at least one file in a package should have a package comment"
      linters:
        - stylecheck
